### ISSUE TITLE
Metrics not getting exposed for prometheus

### ISSUE THREAD

**Issue by poojashukla9219** [launchdarkly/ld-relay#60] opened 2019-05-06 12:42 UTC
On running ld-relay and prometheus on kubernetes, Metrics are not exported by ld-relay. 
LD relay configuration used : 
`[prometheus]
      enabled = true
      port = 9100
      prefix = ""`

K8s conf for service monitor : 
`---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ld-service-monitor
  labels:
    app: ld-relay
spec:
  selector:
    matchLabels:
      app: ld-relay
    namespaceSelector:
      matchNames:
      - <namespace>
  endpoints:
  - port: metrics
    interval: 10s
    honorLabels: true`

Prometheus is scraping the specified endpoint, but data is not being exported to localhost:9100/metrics by ld-relay.

Also, no error messages are present in ld-relay logs.

**Comment by eli-darkly** [comment] 2019-05-08 16:54
Hi, thanks for getting in touch.

We're looking into what might be going on. Initial testing _not_ with Kubernetes suggests that it is possible to see metrics at that endpoint, i.e. at least it is not completely broken. So, in trying to imagine what difference containerization might make, one obvious thought is that it could involve connectivity issues, not being able to reach a specific port, etc. But, you did say that "Prometheus is scraping the specified endpoint", which sounds like you are sure that it made successful requests. Could you clarify exactly what kind of evidence you saw of that?

Also, one reason why no metrics might be seen could be that none were produced. That is, if there had not been any client activity involving the relay yet, there would be no data. Should I assume that you have reason to think that's not the case?

**Comment by eli-darkly** [comment] 2019-05-08 18:22
Also, are you able to test the metrics endpoint without running Prometheus? That is, start the relay, make sure there has been some activity on it, and then use curl or a similar tool to query localhost:9100/metrics.

**Comment by poojashukla9219** [comment] 2019-05-09 12:25
Thanks for the response. 
1. Evidence for prometheus scraping the endpoints : I checked the metrics for prometheus server and it showed successful connection count as well as scrape time for ld-relay server. 
net_conntrack_dialer_conn_established_total{dialer_name="<namespace of ld relay>/ld-service-monitor/0"} 13
prometheus_sd_discovered_targets{config="<namespace of ld relay>/ld-service-monitor/0",name="scrape"} 8
prometheus_target_sync_length_seconds_count{scrape_job="<namespace of ld relay>/ld-service-monitor/0"} 62590

2.I ensured that there was client activity with relay, as I executed a test script to create 100 new connections and fetch flags with each of those.

3.Querying localhost:9100/metrics gives empty response,
kubectl exec -it ld-relay-stable-79d46bcddb-h8w65 -- curl -i localhost:9100/metrics
HTTP/1.1 200 OK
Content-Length: 0
Content-Type: text/plain; version=0.0.4; charset=utf-8
Date: Mon, 06 May 2019 09:27:47 GMT

**Comment by eli-darkly** [comment] 2019-05-10 00:59
On that third item, is that also a relay instance that has had client activity?

**Comment by poojashukla9219** [comment] 2019-05-10 05:11
Yes, I checked the response for all ld relay instances.

**Comment by genadyk** [comment] 2019-11-13 11:38
Any updates? I face same issue since upgrading from 5.4.4 to 5.8.2.
Logs shows: 
"Failed to export to Prometheus: cannot register the collector: collector has no descriptors"

**Comment by eli-darkly** [comment] 2019-11-13 17:44
@genadyk We were not able to replicate this problem. However, we'll be putting out a release soon that includes an update to a more recent Prometheus OpenMetrics package, so it'd be a good idea to retest once that is out.

**Comment by genadyk** [comment] 2019-12-03 13:21
@eli-darkly When this release is expected? thanks

**Comment by eli-darkly** [comment] 2019-12-05 01:51
Unfortunately there turned out to be some issues with using the newer package, so we are not doing that, but we did find some other issues with the current implementation which we are fixing now. Sorry for the delay.

**Comment by genadyk** [comment] 2019-12-18 10:00
@eli-darkly  any update on the issue? Estimated release date?

**Comment by eli-darkly** [comment] 2019-12-18 19:34
As soon as we can. I'm sorry I can't be more helpful in providing a date, but there were multiple problems (one of which involved us having to submit a PR to another open-source project) and testing the Prometheus integration is not straightforward.

**Comment by eli-darkly** [comment] 2019-12-18 19:34
I promise we have not forgotten about the issue.

**Comment by eli-darkly** [comment] 2019-12-20 00:55
OK, we have identified the problem (an incompatible dependency version - i.e. the previous update to a newer Prometheus library was not really completed) and have also added a test for it, and we should have a new release shortly.

@genadyk This particular problem was only present in 5.8.2; as far as I can tell, the integration was working properly in 5.8.1 so an interim solution would be just to not update to the _very_ latest version. I still do not know what was going on with @poojashukla9219's original problem report, which happened before the 5.8.2 release; it's possible that there was some other bug, but if so we were unable to reproduce it.

**Comment by bwoskow-ld** [comment] 2019-12-20 17:58
The issue @genadyk mentioned is fixed in [5.9.0](https://github.com/launchdarkly/ld-relay/releases/tag/5.9.0).

@poojashukla9219 can you check in 5.9.0 and see if your issue remains?

**Comment by eli-darkly** [comment] 2020-01-09 22:41
@genadyk @poojashukla9219 There's been no comment here for a few weeks; could either of you verify whether this is working for you now?

**Comment by genadyk** [comment] 2020-01-12 09:55
Works as expected @eli-darkly . Thanks.

**Comment by eli-darkly** [comment] 2020-01-15 21:20
Closing this issue as presumed fixed, but @poojashukla9219, please feel free to reopen it if you're still having a problem.

**Closed as completed by eli-darkly** 2020-01-15 21:20 UTC
